# base image
FROM node:18.16.0-alpine as build

# set working directory
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./

# install dependencies
RUN npm install

# copy app source
COPY . .

EXPOSE 3000

# start app
CMD ["npm", "start"]